version: '3'

services:
  postgres:
      image: postgres:10
      restart: always
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=john
        - POSTGRES_DB=editoria 
      volumes:
        - ./data/postgres:/var/lib/postgresql/data
        - ./scripts/test.sql:/docker-entrypoint-initdb.d/test.sql
