version: '3'

services:
  postgres:
      image: postgres:10
      restart: always
      ports:
        - 5460:5432
      environment:
        - POSTGRES_USER=dev
        - POSTGRES_DB=editoria_dev 
        - POSTGRES_PASSWORD=secretpassword
      volumes:
        - ./data/postgres:/var/lib/postgresql/data
        - ./scripts/test.sql:/docker-entrypoint-initdb.d/test.sql