version: '3'

services:
  postgres:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $USER
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./scripts/test.sql:/docker-entrypoint-initdb.d/test.sql

volumes:
  postgres-volume:
