version: '2'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile-production
      args:
        - node_env=${NODE_ENV:-production}
        - server_protocol=${SERVER_PROTOCOL}
        - server_host=${SERVER_HOST}
        - server_port=${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - EDITORIA_FLAVOUR=${EDITORIA_FLAVOUR:-VANILLA}
      - PUBSWEET_SECRET=${PUBSWEET_SECRET}
      - SERVES_CLIENT=${SERVES_CLIENT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
      - ADMIN_GIVEN_NAME=${ADMIN_GIVEN_NAME:-Admin}
      - ADMIN_SURNAME=${ADMIN_SURNAME:-Adminius}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - SERVER_PORT=${SERVER_PORT}
      - EXTERNAL_SERVER_URL=${EXTERNAL_SERVER_URL:-null}
      - CLIENT_PROTOCOL=${CLIENT_PROTOCOL}
      - CLIENT_HOST=${CLIENT_HOST}
      - CLIENT_PORT=${CLIENT_PORT}
      - MAILER_USER=${MAILER_USER}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
      - MAILER_SENDER=${MAILER_SENDER}
      - MAILER_HOSTNAME=${MAILER_HOSTNAME}
      - PASSWORD_RESET_PATH=${PASSWORD_RESET_PATH}
      - S3_PROTOCOL=${S3_PROTOCOL}
      - S3_HOST=${S3_HOST}
      - S3_PORT=${S3_PORT}
      - S3_ACCESS_KEY_ID_ADMIN=${S3_ACCESS_KEY_ID_ADMIN}
      - S3_SECRET_ACCESS_KEY_ADMIN=${S3_SECRET_ACCESS_KEY_ADMIN}
      - S3_ACCESS_KEY_ID_USER=${S3_ACCESS_KEY_ID_USER}
      - S3_SECRET_ACCESS_KEY_USER=${S3_SECRET_ACCESS_KEY_USER}
      - S3_BUCKET=${S3_BUCKET}
      - SERVICE_EPUB_CHECKER_CLIENT_ID=${SERVICE_EPUB_CHECKER_CLIENT_ID}
      - SERVICE_EPUB_CHECKER_SECRET=${SERVICE_EPUB_CHECKER_SECRET}
      - SERVICE_EPUB_CHECKER_PROTOCOL=${SERVICE_EPUB_CHECKER_PROTOCOL}
      - SERVICE_EPUB_CHECKER_HOST=${SERVICE_EPUB_CHECKER_HOST}
      - SERVICE_EPUB_CHECKER_PORT=${SERVICE_EPUB_CHECKER_PORT}
      - SERVICE_ICML_CLIENT_ID=${SERVICE_ICML_CLIENT_ID}
      - SERVICE_ICML_SECRET=${SERVICE_ICML_SECRET}
      - SERVICE_ICML_PROTOCOL=${SERVICE_ICML_PROTOCOL}
      - SERVICE_ICML_HOST=${SERVICE_ICML_HOST}
      - SERVICE_ICML_PORT=${SERVICE_ICML_PORT}
      - SERVICE_PAGEDJS_CLIENT_ID=${SERVICE_PAGEDJS_CLIENT_ID}
      - SERVICE_PAGEDJS_SECRET=${SERVICE_PAGEDJS_SECRET}
      - SERVICE_PAGEDJS_PROTOCOL=${SERVICE_PAGEDJS_PROTOCOL}
      - SERVICE_PAGEDJS_HOST=${SERVICE_PAGEDJS_HOST}
      - SERVICE_PAGEDJS_PORT=${SERVICE_PAGEDJS_PORT}
      - SERVICE_XSWEET_CLIENT_ID=${SERVICE_XSWEET_CLIENT_ID}
      - SERVICE_XSWEET_SECRET=${SERVICE_XSWEET_SECRET}
      - SERVICE_XSWEET_PROTOCOL=${SERVICE_XSWEET_PROTOCOL}
      - SERVICE_XSWEET_HOST=${SERVICE_XSWEET_HOST}
      - SERVICE_XSWEET_PORT=${SERVICE_XSWEET_PORT}
