version: '2'

services:
  client:
    restart: unless-stopped
    build:
      context: ./packages/client
      dockerfile: ./Dockerfile-production
      args:
        - node_env=production
        - server_protocol=${SERVER_PROTOCOL}
        - server_host=${SERVER_HOST}
        - server_port=${SERVER_PORT}
        - server_serve_client=false
        - feature_book_structure=${FEATURE_BOOK_STRUCTURE}
        - feature_upload_docx_files=${FEATURE_UPLOAD_DOCX_FILES}
        - client_ws_min_timeout=${CLIENT_WS_MIN_TIMEOUT:-3000}
        - client_ws_timeout=${CLIENT_WS_TIMEOUT:-30000}

    depends_on:
      - server
    ports:
      - ${CLIENT_PORT}:80
    environment:
      - NODE_ENV=production
      - CLIENT_PORT=${CLIENT_PORT}
      - FEATURE_UPLOAD_DOCX_FILES=${FEATURE_UPLOAD_DOCX_FILES}
      - FEATURE_BOOK_STRUCTURE=${FEATURE_BOOK_STRUCTURE}
      - CLIENT_HOST=${CLIENT_HOST}
      - SERVER_SERVE_CLIENT=false
      - SERVER_PROTOCOL=${SERVER_PROTOCOL}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - CLIENT_WS_MIN_TIMEOUT=3000
      - CLIENT_WS_TIMEOUT=30000

  server:
    restart: unless-stopped
    build:
      context: ./packages/server
      dockerfile: ./Dockerfile-production
    ports:
      - ${SERVER_PORT:-3000}:${SERVER_PORT:-3000}
    environment:
      - NODE_ENV=production
      - EDITORIA_FLAVOUR=${EDITORIA_FLAVOUR}
      - PUBSWEET_SECRET=${PUBSWEET_SECRET}
      - EXTERNAL_SERVER_URL=${EXTERNAL_SERVER_URL}
      - SERVER_SERVE_CLIENT=false
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_GIVEN_NAME=${ADMIN_GIVEN_NAME}
      - ADMIN_SURNAME=${ADMIN_SURNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - SERVER_PROTOCOL=${SERVER_PROTOCOL}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - CLIENT_PROTOCOL=${CLIENT_PROTOCOL}
      - CLIENT_HOST=${CLIENT_HOST}
      - CLIENT_PORT=${CLIENT_PORT}
      - MAILER_USER=${MAILER_USER}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
      - MAILER_SENDER=${MAILER_SENDER}
      - MAILER_HOSTNAME=${MAILER_HOSTNAME}
      - PASSWORD_RESET_PATH=password-reset
      - S3_PROTOCOL=${S3_PROTOCOL}
      - S3_HOST=${S3_HOST}
      - S3_PORT=${S3_PORT}
      - S3_ACCESS_KEY_ID_USER=${S3_ACCESS_KEY_ID_USER}
      - S3_SECRET_ACCESS_KEY_USER=${S3_SECRET_ACCESS_KEY_USER}
      - S3_BUCKET=uploads
      - SERVICE_EPUB_CHECKER_CLIENT_ID=${SERVICE_EPUB_CHECKER_CLIENT_ID}
      - SERVICE_EPUB_CHECKER_SECRET=${SERVICE_EPUB_CHECKER_SECRET}
      - SERVICE_EPUB_CHECKER_PROTOCOL=${SERVICE_EPUB_CHECKER_PROTOCOL}
      - SERVICE_EPUB_CHECKER_HOST=${SERVICE_EPUB_CHECKER_HOST}
      - SERVICE_EPUB_CHECKER_PORT=${SERVICE_EPUB_CHECKER_PORT}
      - SERVICE_ICML_CLIENT_ID=${SERVICE_ICML_CLIENT_ID}
      - SERVICE_ICML_SECRET=${SERVICE_ICML_SECRET}
      - SERVICE_ICML_PROTOCOL=${SERVICE_ICML_PROTOCOL}
      - SERVICE_ICML_HOST=${SERVICE_ICML_HOST}
      - SERVICE_ICML_PORT=${SERVICE_ICML_PORT}
      - SERVICE_PAGEDJS_CLIENT_ID=${SERVICE_PAGEDJS_CLIENT_ID}
      - SERVICE_PAGEDJS_SECRET=${SERVICE_PAGEDJS_SECRET}
      - SERVICE_PAGEDJS_PROTOCOL=${SERVICE_PAGEDJS_PROTOCOL}
      - SERVICE_PAGEDJS_HOST=${SERVICE_PAGEDJS_HOST}
      - SERVICE_PAGEDJS_PORT=${SERVICE_PAGEDJS_PORT}
      - SERVICE_XSWEET_CLIENT_ID=${SERVICE_XSWEET_CLIENT_ID}
      - SERVICE_XSWEET_SECRET=${SERVICE_XSWEET_SECRET}
      - SERVICE_XSWEET_PROTOCOL=${SERVICE_XSWEET_PROTOCOL}
      - SERVICE_XSWEET_HOST=${SERVICE_XSWEET_HOST}
      - SERVICE_XSWEET_PORT=${SERVICE_XSWEET_PORT}
      - FEATURE_UPLOAD_DOCX_FILES=${FEATURE_UPLOAD_DOCX_FILES}
      - FEATURE_BOOK_STRUCTURE=${FEATURE_BOOK_STRUCTURE}